### PR TITLE
feat: add mounts var for CTs creation

### PR DESCRIPTION
**Pull request by achillemyette1**
The `mounts` var is not yet supported on CTs creation.
As per documentation, this enable us to define more than one disk for the containers.

### CODE REVIEW

**Review by pbouchez — APPROVED** [review]

**Review by btravouillon — CHANGES_REQUESTED** [review]
Could you update the README to remove `mounts` from the list below?

> The following parameters are not supported yet, but this might change in future development: `api_password`, `ip_address`, `mounts`, `password`, `pool`, `purge`, `searchdomain` and `storage`.

**Comment by achillemyette1** [comment]
> Could you update the README to remove `mounts` from the list below?
> 
> > The following parameters are not supported yet, but this might change in future development: `api_password`, `ip_address`, `mounts`, `password`, `pool`, `purge`, `searchdomain` and `storage`.

Done

**Comment by btravouillon** [comment]
Could you keep the 80 columns width?

**Comment by achillemyette1** [comment]
> Could you keep the 80 columns width?

done

**Review by btravouillon — DISMISSED** [review]
Looks good to me. 👍

**Review by pbouchez — DISMISSED** [review]

**Comment by achillemyette1** [comment]
Forgot to bump to v0.4.6, can we do it on this PR ?

**Comment by achillemyette1** [comment]
> > Forgot to bump to v0.4.6, can we do it on this PR ?
> 
> No, let's differentiate code changes and releases.

OK my bad, fixed, will need the approvals again...

**Review by btravouillon — APPROVED** [review]

**Pull request merged**
